package main

import (
	"strings"
	"testing"

	"github.com/jbedard/aoc2025/lib"
)

func TestPart1(t *testing.T) {
	input := `
.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............
`
	g := lib.NewCharGridFromSeq(strings.SplitSeq(strings.TrimSpace(input), "\n"))

	splits, beams := part1(g)
	if splits != 21 {
		t.Errorf("expected 21 splits, got %d", splits)
	}
	if beams != 40 {
		t.Errorf("expected 40 beams, got %d", beams)
	}
}
